name: exercism_dart
authors:
  - SuperPaintman <SuperPaintmanDeveloper@gmail.com>
  - Stargator <wildbug@linuxmail.org>
  - fwip
  - kabiir
dev_dependencies:
  args: '^1.0.0'
  dart_style: '^1.0.8'
  io: '0.3.0'
  test: '>=0.12.24+8 <0.13.0'
  yaml: '>=2.1.12 <2.2.0'
