name: exercism_dart
environment:
  sdk: '>=2.18.0 <3.0.0'
authors:
  - SuperPaintman <SuperPaintmanDeveloper@gmail.com>
  - Stargator <wildbug@linuxmail.org>
  - fwip
  - devkabiir
  - jvarness <jake.varness@gmail.com>
dev_dependencies:
  args: '^2.0.0'
  dart_style: '^2.0.0'
  io: '^1.0.0'
  test: '^1.16.0'
  yaml: '^3.0.0'
