name: exercism_dart
environment:
  sdk: '>=3.2.0 <4.0.0'
authors:
  - SuperPaintman <SuperPaintmanDeveloper@gmail.com>
  - Stargator <wildbug@linuxmail.org>
  - fwip
  - devkabiir
  - jvarness <jake.varness@gmail.com>
dev_dependencies:
  args: ^2.4.2
  dart_style: ^2.3.4
  io: ^1.0.4
  test: ^1.25.2
  yaml: ^3.1.2
  collection: ^1.18.0
